version: "3.9"

volumes:
  db-data:

services: 
  vault:
    image: hashicorp/vault-enterprise:1.7.10-ent
    environment: 
    - VAULT_ADDR=http://vault:8200
    - VAULT_TOKEN=root
    - NO_PROXY=vault
    ports:
    - 8200:8200
    command:
      [ vault, server, -dev, -dev-root-token-id, root, -dev-listen-address=0.0.0.0:8200]

  terraform:
    build:
      context: ./provision
      dockerfile: Dockerfile
    environment:
    - VAULT_ADDR=http://vault:8200
    - VAULT_TOKEN=root
    - NO_PROXY=vault
    volumes:
    - ./env:/workdir


  provision:
    build:
      context: ./provision
      dockerfile: Dockerfile
    environment: 
    - VAULT_ADDR=http://vault:8200
    - VAULT_TOKEN=root
    - NO_PROXY=vault
      
  test:
    build:
      context: ./test
      dockerfile: Dockerfile
    environment: 
    - VAULT_ADDR=http://vault:8200
    - VAULT_TOKEN=root
    - NO_PROXY=vault
    volumes:
    - ./test:/workdir
